os:
  - osx

osx_image:
  - xcode9.2

install:
  - export PATH="/usr/local/opt/python/libexec/bin:$PATH"
  - brew update
  - brew cleanup
  - brew upgrade python
  - brew tap liamg/tfsec
  - brew install liamg/tfsec/tfsec
  - brew install secrethub/tools/secrethub-cli
  - pip install -r requirements.txt

# TODO: Add ansible_vault_password
# env:
#  - ANSIBLE_VAULT_PASSWORD="secrethub://vidal/ops/ops-tools/vault_pass.txt"

script:
  - tfsec .
  - ansible-lint
# TODO: Add ansible playbook provisioning
#  - cd ansible
#  - secrethub run -- ansible-playbook playbooks/analytics.yml --vault-password-file=ansible_vault_password.py
