language: python

python:
  - "3.7"

compiler:
  - g++-5

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - pip install -r requirements.txt
  - brew tap liamg/tfsec
  - brew install liamg/tfsec/tfsec

  before_script:
  - tfsec .

script:
  - pytest

os:
  - osx
