os:
  - osx

osx_image:
  - xcode9.2

install:
  - export PATH="/usr/local/opt/python/libexec/bin:$PATH"
  - brew update
  - brew cleanup
  - brew upgrade python
  - brew tap liamg/tfsec
  - brew install liamg/tfsec/tfsec
  - pip install -r requirements.txt

script:
  - tfsec .
