os:
  - osx

osx_image:
  - xcode9.2

compiler:
  - g++-5

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - brew update
  - brew unlink python@2
  - brew upgrade python
  - brew link --overwrite python
  - brew tap liamg/tfsec
  - brew install liamg/tfsec/tfsec
  - pip install -r requirements.txt

before_script:
  - tfsec .

script:
  - pytest
