- name: Install metabase
  homebrew:
    name: metabase
    state: present

- name: Register metabase keg path
  command: "greadlink -f {{ brew_prefix }}/bin/metabase"
  register: brew_metabase_path_register

- name: Set metabase keg path
  set_fact:
    brew_metabase_path: "{{ brew_metabase_path_register.stdout }}"

- name: Set metabase plist path
  set_fact:
    brew_metabase_plist_path: "{{ brew_metabase_path | regex_replace('/bin/metabase', '') }}"

- name: Copy brew metabase plist.
  template:
    src: ../templates/homebrew.mxcl.metabase.plist.j2
    dest: "{{ brew_metabase_plist_path }}/homebrew.mxcl.metabase.plist"

- name: Start metabase
  shell: brew services start metabase

- name: Set metabase session
  uri:
    url: "http://127.0.0.1:{{ metabase_port }}/api/session/properties"
    status_code: 200
  register: metabase_api_session
  until: metabase_api_session is not failed
  retries: 40
  delay: 6

- name: Submit initial configuration
  uri:
    url: "http://127.0.0.1:{{ metabase_port }}/api/setup"
    method: POST
    body:
      token: "{{ metabase_api_session.json['setup-token'] }}"
      user:
        first_name: "{{ metabase_admin_credentials.first_name }}"
        last_name: "{{ metabase_admin_credentials.last_name }}"
        email: "{{ metabase_admin_credentials.email }}"
        password: "{{ metabase_admin_credentials.password }}"
      prefs:
        site_name: "{{ metabase_prefs.site_name }}"
        allow_tracking: "{{ metabase_prefs.allow_tracking }}"
    body_format: json
    status_code: 200
    headers:
      Accept: "application/json"
      Content-Type: "application/json"
  register: metabase_api_setup
  no_log: true
  when: metabase_api_session and metabase_api_session.json['setup-token'] 
