- name: Start MySQL service
  docker_compose:
    project_name: mysql
    definition:
      version: '3.3'
      services:
        mysql_db:
          image: mysql:5.7
          restart: always
          environment:
            MYSQL_ROOT_PASSWORD: "{{ mysql_admin_credentials.root_password }}"
          ports:
            - "{{ mysql_port }}:3306"
          expose:
            - 3306
          volumes:
            - mysql_data:/var/lib/mysql
      volumes:
        mysql_data:
  register: mysql_docker_register
  no_log: true

- name: Ensure mysql user is present.
  mysql_user:
    name: "{{ mysql_admin_credentials.name }}"
    password: "{{ mysql_admin_credentials.password }}"
    priv: '*.*:ALL,GRANT'
    state: present
    host: "%"
    login_user: root
    login_password: "{{ mysql_admin_credentials.root_password }}"
    login_port: "{{ mysql_port }}"
    login_host: "{{ docker_machine_ip }}"
  when: mysql_admin_credentials.name != "root"
  register: task_result
  retries: 40
  delay: 6
  until: task_result is not failed
  no_log: true
