- name: Setup analytics
  hosts: localhost

  vars:
    analytics_mysql_port: 3307
    analytics_database: data

  tasks:
    - name: Register brew prefix
      command: brew --prefix
      register: brew_prefix_path_register
      changed_when:
        - brew_prefix_path_register.rc == 0
    - name: Set brew prefix path
      set_fact:
        brew_prefix_path: "{{ brew_prefix_path_register.stdout }}"
    - name: register docker-machine ip
      command: docker-machine ip
      register: docker_machine_ip_register
      changed_when:
        - docker_machine_ip_register.rc == 0
    - name: Set docker-machine ip
      set_fact:
        analytics_docker_machine_ip: "{{ docker_machine_ip_register.stdout }}"
    - name: Include vars of secrets/mysql_admin.yaml .
      include_vars:
        file: ../secrets/mysql_admin.yml
        name: mysql_admin
      no_log: true
    - name: Provision mysql
      include_role:
        name: mysql
      vars:
        mysql_admin_credentials: "{{ mysql_admin }}"
        brew_prefix: "{{ brew_prefix_path }}"
        mysql_port: "{{ analytics_mysql_port }}"
        mysql_database: "{{ analytics_database }}"
        docker_machine_ip: "{{ analytics_docker_machine_ip }}"
    - name: Provision data in mysql
      include_role:
        name: data
      vars:
        mysql_admin_credentials: "{{ mysql_admin }}"
        mysql_port: "{{ analytics_mysql_port }}"
        mysql_host: "{{ analytics_docker_machine_ip }}"
        mysql_database: "{{ analytics_database }}"
