- name: Setup analytics
  hosts: localhost

  vars:
    metabase_options:
      use_own_database: false

  tasks:
    - name: Register brew prefix
      command: brew --prefix
      register: brew_prefix_path_register

    - name: Set brew prefix path
      set_fact:
        brew_prefix_path: "{{ brew_prefix_path_register.stdout }}"

    - name: Provision virtualenv
      include_role:
        name: virtualenv
    - name: Include metabase admin vars
      include_vars:
        file: ../secrets/metabase_admin.yml
        name: metabase_admin
      no_log: true
    - name: Provision metabase
      include_role:
        name: metabase
      vars:
        metabase_admin_credentials: "{{ metabase_admin }}"
        brew_prefix: "{{ brew_prefix_path }}"
    - name: Include vars of secrets/mysql_admin.yaml .
      include_vars:
        file: ../secrets/mysql_admin.yml
        name: mysql_admin
      no_log: true
    - name: Provision mysql
      include_role:
        name: mysql
      vars:
        mysql_admin_credentials: "{{ mysql_admin }}"
        brew_prefix: "{{ brew_prefix_path }}"
