- name: Setup analytics
  hosts: localhost

  vars:
    analytics_mysql_port: 3307
    analytics_database: data

  tasks:
    - name: register minikube ip
      command: minikube ip
      register: minikube_ip_register
      changed_when:
        - minikube_ip_register.rc == 0
    - name: Set minikube ip
      set_fact:
        analytics_minikube_ip: "{{ minikube_ip_register.stdout }}"
    - name: Include vars of secrets/mysql_admin.yaml .
      include_vars:
        file: ../secrets/mysql_admin.yml
        name: mysql_admin
      no_log: true
    - name: Provision mysql
      include_role:
        name: mysql
      vars:
        mysql_admin_credentials: "{{ mysql_admin }}"
        brew_prefix: "{{ brew_prefix_path }}"
        mysql_port: "{{ analytics_mysql_port }}"
        mysql_database: "{{ analytics_database }}"
        minikube_ip: "{{ analytics_minikube_ip }}"
    - name: Provision data in mysql
      include_role:
        name: data
      vars:
        mysql_admin_credentials: "{{ mysql_admin }}"
        mysql_port: "{{ analytics_mysql_port }}"
        mysql_host: "{{ analytics_minikube_ip }}"
        mysql_database: "{{ analytics_database }}"
