metabase_port: 3002

metabase_prefs:
  site_name: Metabase
  allow_tracking: false

metabase_admin_credentials:
  first_name: Metabase
  last_name: Admin
  email: example@example.com
  password: metabase123

brew_prefix: /usr/local
